@host = http://localhost:8080

### Sign Up
POST {{host}}/signup
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

### Login
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}
